### ISSUE TITLE
obs doc not parsed?

### ISSUE THREAD

**Issue by caseyjlaw** [demorest/evla_mcast#6]
This problem seems to be special to some obs docs I've seen during testing. Mostly, things work, but a recent observation for program 17A-283 (using recirculation?) failed with this error:

```2017-08-10 10:43:51,953 - evla_mcast.mcast_clients - ERROR - error handling 'obs' message
Traceback (most recent call last):
  File "/home/cbe-master/realfast/anaconda/envs/development/lib/python2.7/site-packages/evla_mcast/mcast_clients.py", line 68, in handle_read
    self.parse()
  File "/home/cbe-master/realfast/anaconda/envs/development/lib/python2.7/site-packages/evla_mcast/mcast_clients.py", line 95, in parse
    .format(obs.attrib['configId'], obs.attrib['seq']))
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70080)
KeyError: 'configId'
```
This attribute is read by a logging statement in the ObsClient parse function.
Is there something special about some programs that produces nonstandard obs docs?

**Comment by caseyjlaw** [comment]
Perhaps related... I see two other odd errors in multicast message parsing.
First, my logging of this antenna doc shows an odd name:
```
2017-08-10 10:55:03,038 - evla_mcast.mcast_clients - INFO - Read ant datasetId=SOFTWARE.servotrack.evla.57975.704866597225
```

Then, the next obs doc has a different error on parsing:
```
2017-08-10 10:55:03,040 - evla_mcast.mcast_clients - ERROR - error handling 'obs' message
Traceback (most recent call last):
  File "/home/cbe-master/realfast/anaconda/envs/development/lib/python2.7/site-packages/evla_mcast/mcast_clients.py", line 68, in handle_read
    self.parse()
  File "/home/cbe-master/realfast/anaconda/envs/development/lib/python2.7/site-packages/evla_mcast/mcast_clients.py", line 93, in parse
    obs = objectify.fromstring(self.read, parser=_obs_parser)
  File "src/lxml/lxml.objectify.pyx", line 1804, in lxml.objectify.fromstring (src/lxml/lxml.objectify.c:25895)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79010)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
XMLSyntaxError: Element 'scanNo': This element is not expected. Expected is ( intent ). (line 0)
2017-08-10 10:55:07,054 - evla_mcast.mcast_clients - ERROR - error handling 'obs' message
Traceback (most recent call last):
  File "/home/cbe-master/realfast/anaconda/envs/development/lib/python2.7/site-packages/evla_mcast/mcast_clients.py", line 68, in handle_read
    self.parse()
  File "/home/cbe-master/realfast/anaconda/envs/development/lib/python2.7/site-packages/evla_mcast/mcast_clients.py", line 95, in parse
    .format(obs.attrib['configId'], obs.attrib['seq']))
  File "src/lxml/lxml.etree.pyx", line 2452, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70080)
KeyError: 'configId'
```

Soon after this, several messages from the same program were parsed well.
I should add that this is my fork, not yours. I suppose I could have introduced a bug when making some of the style changes. If you don't see any obvious problem on your side, I'll try to run your fork instead.

**Comment by demorest** [comment]
hi Casey, do you have the original obs documents from these examples saved?  That would be best for debugging.

Any observation that starts with "SOFTWARE" means it was run from a special test version of the executor, ie something non-standard was being done.  So I wouldn't worry too much about errors on those...

The configId key error is a bit strange.  Some test/maintenance scripts do not use the correlator so might result in missing configId; I've never looked closely at how the obs doc for these ones look.  But I would not expect this for an actual science observation.

**Comment by caseyjlaw** [comment]
I don't have an example saved. It happens sporadically, so it will be hard to catch. Maybe that indicates it is sensitive to the recent history of obs messages?
Anyway, I'll update this thread if I see better examples.

**Comment by caseyjlaw** [comment]
A related issue, maybe...
I parsed using scan_config and tried to catch data with vysmaw. I expected
351 baselines, but often it seemed that 325 baselines arrive, like one
antenna was missing. Is it possible to have the antenna list change
relative to the config object?
